#!/bin/csh
cd ../..
cvs co -r CMSSW_1_0_6 Configuration/Examples/data/RECO.cff
cp -r ~cbern/public/CMSSW/CMSSW_1_0_6/RECO.cff Configuration/Examples/data/RECO.cvs co -r SimVertexInMM FastSimulation/Event
